### PR TITLE
feat: add support for Polygon Amoy

### PR DESCRIPTION
**Pull request by derekpierre**
### What I did

fixes: #75 

### How I did it
Added "amoy" as a valid network, and added amoy's chain id for poa support.

### Checklist

- [X] Passes all linting checks (pre-commit and CI jobs)
- [ ] New test cases have been added and are passing
- [ ] Documentation has been updated
- [X] PR title follows [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) standard (will be automatically included in the changelog)

### CODE REVIEW

**Review by fubuloubu — APPROVED** [review]

**Review by antazoey — APPROVED** [review]

**Comment by fubuloubu** [comment]
seems like this is failing due to 401 on polygon amoy endpoint

**Comment by antazoey** [comment]
@fubuloubu I am working on it, unless you are?

**Comment by antazoey** [comment]
@fubuloubu Actually, I don't have access to our infura account so either I need access or someone else has to go in an check the box for Amoy.

**Comment by fubuloubu** [comment]
I just enabled them

**Comment by antazoey** [comment]
i see a green check, musta werked

**Pull request merged**
